# Generated by Django 3.2 on 2022-09-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatManageTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('level_two', models.IntegerField(blank=True, null=True)),
                ('level_three', models.IntegerField(blank=True, null=True)),
                ('level_four', models.IntegerField(blank=True, null=True)),
                ('level_five', models.IntegerField(blank=True, null=True)),
                ('level_six', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_manage_svg_files',
            },
        ),
        migrations.CreateModel(
            name='ManageSocialIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.ImageField(blank=True, null=True, upload_to='social')),
                ('google', models.ImageField(blank=True, null=True, upload_to='social')),
                ('twitter', models.ImageField(blank=True, null=True, upload_to='social')),
                ('instagram', models.ImageField(blank=True, null=True, upload_to='social')),
                ('pinterest', models.ImageField(blank=True, null=True, upload_to='social')),
                ('snapchat', models.ImageField(blank=True, null=True, upload_to='social')),
                ('messenger', models.ImageField(blank=True, null=True, upload_to='social')),
                ('tiktok', models.ImageField(blank=True, null=True, upload_to='social')),
                ('whatsapp', models.ImageField(blank=True, null=True, upload_to='social')),
            ],
            options={
                'db_table': 'cat-manage-social-icons',
            },
        ),
    ]
