# Generated by Django 3.2 on 2022-09-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lashguru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBrandFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('positive_files', models.ImageField(height_field=300, upload_to='positive_files', width_field=500)),
                ('negative_files', models.ImageField(height_field=300, upload_to='negative_files', width_field=500)),
                ('colored_files', models.ImageField(height_field=300, upload_to='colored_files', width_field=500)),
            ],
            options={
                'db_table': 'add_brand_fields',
            },
        ),
        migrations.CreateModel(
            name='CatManageTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_cat', models.CharField(choices=[('Service', 'Service'), ('Content', 'Content'), ('Review', 'Review')], max_length=200)),
                ('content', models.JSONField(help_text='Json content in here!')),
                ('template_files', models.ImageField(blank=True, null=True, upload_to='template_content')),
            ],
            options={
                'db_table': 'cat-manage.templates',
            },
        ),
    ]
